# Generated by Django 4.0.1 on 2022-01-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdharCardDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.BigIntegerField(verbose_name='Adhar Aumber')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name in English')),
                ('relation', models.CharField(choices=[('S/O', 'S/O'), ('D/O', 'D/O'), ('W/O', 'W/O')], default='S/O', max_length=4, verbose_name='Relation')),
                ('relation_name', models.CharField(max_length=100, verbose_name='Relation(Father/Husband) Name in English')),
                ('date_of_birth', models.DateField(null=True, verbose_name='DOB')),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=8, verbose_name='Gender')),
                ('image', models.ImageField(upload_to='profile_image', verbose_name='Image')),
                ('address', models.CharField(max_length=150, verbose_name='Full Address in English')),
                ('state', models.CharField(choices=[('Chhattisgarh', 'Chhattisgarh'), ('Madhya Pradesh', 'Madhya Pradesh')], default='Madhya Pradesh', max_length=20, verbose_name='State')),
                ('pin_code', models.CharField(default='482000', max_length=6, verbose_name='PIN CODE')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
