# Generated by Django 4.0.1 on 2022-01-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printAdhar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adharcarddetail',
            name='gender',
            field=models.CharField(choices=[('FEMALE', 'FEMALE'), ('MALE', 'MALE')], default='MALE', max_length=8, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='adharcarddetail',
            name='relation',
            field=models.CharField(choices=[('S/O', 'S/O'), ('W/O', 'W/O'), ('D/O', 'D/O')], default='S/O', max_length=4, verbose_name='Relation'),
        ),
        migrations.AlterField(
            model_name='adharcarddetail',
            name='state',
            field=models.CharField(choices=[('Madhya Pradesh', 'Madhya Pradesh'), ('Chhattisgarh', 'Chhattisgarh')], default='Madhya Pradesh', max_length=20, verbose_name='State'),
        ),
    ]
