# Generated by Django 4.0.1 on 2022-01-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printAdhar', '0002_alter_adharcarddetail_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adharcarddetail',
            name='city',
            field=models.CharField(default='Singrauli', max_length=20, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adharcarddetail',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=8, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='adharcarddetail',
            name='relation',
            field=models.CharField(choices=[('W/O', 'W/O'), ('D/O', 'D/O'), ('S/O', 'S/O')], default='S/O', max_length=4, verbose_name='Relation'),
        ),
    ]
