# Generated by Django 4.0.1 on 2022-01-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printAdhar', '0003_adharcarddetail_city_alter_adharcarddetail_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adharcarddetail',
            name='address_hi',
            field=models.CharField(default='a', max_length=150, verbose_name='Address (Hindi)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adharcarddetail',
            name='city_hi',
            field=models.CharField(default='w', max_length=20, verbose_name='City (Hindi)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adharcarddetail',
            name='full_name_hi',
            field=models.CharField(default='e', max_length=100, verbose_name='Full Name (Hindi)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adharcarddetail',
            name='gender_hi',
            field=models.CharField(default='df', max_length=20, verbose_name='Gender (Hindi)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adharcarddetail',
            name='relation_hi',
            field=models.CharField(default='sdf', max_length=20, verbose_name='Relation (hindi)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adharcarddetail',
            name='relation_name_hi',
            field=models.CharField(default='sef', max_length=100, verbose_name='Father/Husband (Hindi)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adharcarddetail',
            name='state_hi',
            field=models.CharField(default='sef', max_length=50, verbose_name='State (Hindi)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adharcarddetail',
            name='address',
            field=models.CharField(max_length=150, verbose_name='Address (English)'),
        ),
        migrations.AlterField(
            model_name='adharcarddetail',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Full Name (English)'),
        ),
        migrations.AlterField(
            model_name='adharcarddetail',
            name='relation',
            field=models.CharField(choices=[('D/O', 'D/O'), ('S/O', 'S/O'), ('W/O', 'W/O')], default='S/O', max_length=4, verbose_name='Relation'),
        ),
        migrations.AlterField(
            model_name='adharcarddetail',
            name='relation_name',
            field=models.CharField(max_length=100, verbose_name='Father/Husband (English)'),
        ),
    ]
